#!/usr/bin/env bash

# Source this file before running the backend on Raspberry Pi.
# It keeps the full local voice pipeline, but caps CPU-heavy pieces for latency.

export ECHO_PROFILE="${ECHO_PROFILE:-pi-fast}"

export OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:0.5b}"
export OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-1h}"
export OLLAMA_NUM_CTX="${OLLAMA_NUM_CTX:-1024}"
export OLLAMA_NUM_THREAD="${OLLAMA_NUM_THREAD:-4}"

export ECHO_LLM_NUM_PREDICT="${ECHO_LLM_NUM_PREDICT:-72}"
export ECHO_LLM_TTS_FLUSH_CHARS="${ECHO_LLM_TTS_FLUSH_CHARS:-60}"

export ECHO_WHISPER_THREADS="${ECHO_WHISPER_THREADS:-4}"
export ECHO_WHISPER_VAD="${ECHO_WHISPER_VAD:-1}"
export ECHO_WHISPER_TIMEOUT="${ECHO_WHISPER_TIMEOUT:-12}"

export ECHO_TTS_SPEED="${ECHO_TTS_SPEED:-1.14}"
export ECHO_TTS_MAX_CHUNK_LENGTH="${ECHO_TTS_MAX_CHUNK_LENGTH:-90}"
export ECHO_TTS_SILENCE_DURATION="${ECHO_TTS_SILENCE_DURATION:-0.03}"
export ECHO_PIPER_TIMEOUT="${ECHO_PIPER_TIMEOUT:-12}"

export ECHO_ENDPOINT_RMS_THRESHOLD="${ECHO_ENDPOINT_RMS_THRESHOLD:-0.016}"
export ECHO_ENDPOINT_MIN_SPEECH_MS="${ECHO_ENDPOINT_MIN_SPEECH_MS:-120}"
export ECHO_VAD_MIN_SILENCE_MS="${ECHO_VAD_MIN_SILENCE_MS:-480}"
export ECHO_VAD_SPEECH_PAD_MS="${ECHO_VAD_SPEECH_PAD_MS:-120}"
export ECHO_VAD_PREROLL_MS="${ECHO_VAD_PREROLL_MS:-180}"
export ECHO_VAD_MAX_SECONDS="${ECHO_VAD_MAX_SECONDS:-5.5}"
export ECHO_WAKE_LISTEN_TIMEOUT="${ECHO_WAKE_LISTEN_TIMEOUT:-5.5}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
